# Generated by Django 3.2 on 2021-04-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0003_auto_20210416_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='InfoContact',
        ),
    ]
